/**
 * Generated by orval v7.6.0 🍺
 * Do not edit manually.
 * TrinityKitWP API
 * API para criar posts e fazer upload de imagens no WordPress
 * OpenAPI spec version: 1.0.0
 */

export type GetProductLineSlug200DataParent = {
  /** Nome da linha de produto */
  name?: string;
  /** Slug da linha de produto */
  slug?: string;
  /** Descrição da linha de produto */
  description?: string;
  images?: string[];
};
