/**
 * Generated by orval v7.6.0 🍺
 * Do not edit manually.
 * TrinityKitWP API
 * API para criar posts e fazer upload de imagens no WordPress
 * OpenAPI spec version: 1.0.0
 */

export type GetProductLineSlugs200DataItem = {
  /** ID da linha de produto */
  id?: number;
  /** Título da linha de produto */
  title?: string;
  /** Slug da linha de produto */
  slug?: string;
};
