/**
 * Generated by orval v7.6.0 🍺
 * Do not edit manually.
 * TrinityKitWP API
 * API para criar posts e fazer upload de imagens no WordPress
 * OpenAPI spec version: 1.0.0
 */

export type GetPostSlugsParams = {
/**
 * Quantidade total de posts a retornar. Se não especificado, retorna todos os posts.
 */
quantity?: number;
/**
 * Quantidade de posts por página para paginação. Se especificado, ignora o parâmetro quantity.
 */
per_page?: number;
/**
 * Número da página desejada (começa em 1). Só tem efeito se per_page for especificado.
 */
page?: number;
};
