/**
 * Generated by orval v7.6.0 🍺
 * Do not edit manually.
 * TrinityKitWP API
 * API para criar posts e fazer upload de imagens no WordPress
 * OpenAPI spec version: 1.0.0
 */
import type { GetPostSlug401Data } from './getPostSlug401Data';

export type GetPostSlug401 = {
  code?: string;
  message?: string;
  data?: GetPostSlug401Data;
};
