/**
 * Generated by orval v7.6.0 🍺
 * Do not edit manually.
 * TrinityKitWP API
 * API para criar posts e fazer upload de imagens no WordPress
 * OpenAPI spec version: 1.0.0
 */
import type { GetProductLineSlug200Data } from './getProductLineSlug200Data';

export type GetProductLineSlug200 = {
  success?: boolean;
  data?: GetProductLineSlug200Data;
  /** Número total de produtos retornados */
  items?: number;
};
