/**
 * Generated by orval v7.6.0 🍺
 * Do not edit manually.
 * TrinityKitWP API
 * API para criar posts e fazer upload de imagens no WordPress
 * OpenAPI spec version: 1.0.0
 */
import type { GetProductLineSlugs200DataItem } from './getProductLineSlugs200DataItem';

export type GetProductLineSlugs200 = {
  success?: boolean;
  data?: GetProductLineSlugs200DataItem[];
};
