/**
 * Generated by orval v7.6.0 🍺
 * Do not edit manually.
 * TrinityKitWP API
 * API para criar posts e fazer upload de imagens no WordPress
 * OpenAPI spec version: 1.0.0
 */
import type { TaxonomyTerm } from './taxonomyTerm';

export type GetProducts200DataItemProductLinesItem = {
  /** ID da linha de produto */
  id?: number;
  /** Nome da linha de produto */
  name?: string;
  /** Slug da linha de produto */
  slug?: string;
  /** Linhas de produto filhas */
  children?: TaxonomyTerm[];
};
