/**
 * Generated by orval v7.6.0 🍺
 * Do not edit manually.
 * TrinityKitWP API
 * API para criar posts e fazer upload de imagens no WordPress
 * OpenAPI spec version: 1.0.0
 */
import type { GetSegmentSlug200DataItemSegmentsItem } from './getSegmentSlug200DataItemSegmentsItem';
import type { GetSegmentSlug200DataItemProductLinesItem } from './getSegmentSlug200DataItemProductLinesItem';

export type GetSegmentSlug200DataItem = {
  /** ID do produto */
  id?: number;
  /** Título do produto */
  title?: string;
  /** Número CAS do produto */
  cas_number?: string;
  segments?: GetSegmentSlug200DataItemSegmentsItem[];
  product_lines?: GetSegmentSlug200DataItemProductLinesItem[];
};
