/**
 * Generated by orval v7.6.0 🍺
 * Do not edit manually.
 * TrinityKitWP API
 * API para criar posts e fazer upload de imagens no WordPress
 * OpenAPI spec version: 1.0.0
 */
import type { GetSegmentSlug401Data } from './getSegmentSlug401Data';

export type GetSegmentSlug401 = {
  code?: string;
  message?: string;
  data?: GetSegmentSlug401Data;
};
