/**
 * Generated by orval v7.6.0 🍺
 * Do not edit manually.
 * TrinityKitWP API
 * API para criar posts e fazer upload de imagens no WordPress
 * OpenAPI spec version: 1.0.0
 */
import type { GetSegmentSlug200DataItem } from './getSegmentSlug200DataItem';

export type GetSegmentSlug200 = {
  success?: boolean;
  data?: GetSegmentSlug200DataItem[];
  /** Número total de produtos retornados */
  items?: number;
};
