/**
 * Generated by orval v7.6.0 🍺
 * Do not edit manually.
 * TrinityKitWP API
 * API para criar posts e fazer upload de imagens no WordPress
 * OpenAPI spec version: 1.0.0
 */

export type GetSegmentSlug200DataItemSegmentsItem = {
  /** ID do segmento */
  id?: number;
  /** Nome do segmento */
  name?: string;
  /** Slug do segmento */
  slug?: string;
};
