/**
 * Generated by orval v7.6.0 🍺
 * Do not edit manually.
 * TrinityKitWP API
 * API para criar posts e fazer upload de imagens no WordPress
 * OpenAPI spec version: 1.0.0
 */

export * from './getConfigs200';
export * from './getConfigs200Data';
export * from './getConfigs401';
export * from './getConfigs401Data';
export * from './getPostSlugs200';
export * from './getPostSlugs200DataItem';
export * from './getPostSlugs401';
export * from './getPostSlugs401Data';
export * from './getProducts200';
export * from './getProducts200DataItem';
export * from './getProducts200DataItemProductLinesItem';
export * from './getProducts200DataItemSegmentsItem';
export * from './getProducts401';
export * from './getProducts401Data';
export * from './getSegmentSlug200';
export * from './getSegmentSlug200DataItem';
export * from './getSegmentSlug200DataItemProductLinesItem';
export * from './getSegmentSlug200DataItemSegmentsItem';
export * from './getSegmentSlug200Segment';
export * from './getSegmentSlug401';
export * from './getSegmentSlug401Data';
export * from './getSegmentSlug404';
export * from './getSegmentSlug404Data';
export * from './postContactFormSubmit200';
export * from './postContactFormSubmit400';
export * from './postContactFormSubmit400Data';
export * from './postContactFormSubmit401';
export * from './postContactFormSubmit401Data';
export * from './postContactFormSubmit500';
export * from './postContactFormSubmit500Data';
export * from './postContactFormSubmitBody';
export * from './taxonomyTerm';