/**
 * Generated by orval v7.6.0 🍺
 * Do not edit manually.
 * TrinityKitWP API
 * API para criar posts e fazer upload de imagens no WordPress
 * OpenAPI spec version: 1.0.0
 */
import type { PostContactFormSubmit400Data } from './postContactFormSubmit400Data';

export type PostContactFormSubmit400 = {
  code?: string;
  message?: string;
  data?: PostContactFormSubmit400Data;
};
