/**
 * Generated by orval v7.6.0 🍺
 * Do not edit manually.
 * TrinityKitWP API
 * API para criar posts e fazer upload de imagens no WordPress
 * OpenAPI spec version: 1.0.0
 */

export type PostContactFormSubmitBody = {
  /** Nome do contato (obrigatório) */
  name: string;
  /** Email do contato (obrigatório) */
  email: string;
  /** Telefone do contato (obrigatório) */
  phone: string;
  /** Mensagem do contato (obrigatório) */
  message: string;
  /** Tag para categorizar o contato (obrigatório) */
  tag: string;
  /** Arquivo anexo (opcional). Formatos permitidos: PDF, XLS, XLSX, CSV, DOC, DOCX, JPG, JPEG, PNG, GIF, SVG, WEBP. Tamanho máximo: 10MB */
  attachment?: Blob;
};
