/**
 * Generated by orval v7.6.0 🍺
 * Do not edit manually.
 * TrinityKitWP API
 * API para criar posts e fazer upload de imagens no WordPress
 * OpenAPI spec version: 1.0.0
 */

export type PostContactFormSubmitBody = {
  /** Nome do contato */
  name: string;
  /** Email do contato */
  email: string;
  /** Telefone do contato */
  phone: string;
  /** Mensagem do contato */
  message: string;
  /** Tag opcional para categorizar o contato */
  tag?: string;
};
